### PR TITLE
docs(prs): Clarify automatic PR comment text

### LINKED ISSUE #84: Clarify to `run jobs` after repo-local CI checks have passed
I've been using Plone's Jenkins through the `mister-roboto` bot comment `@jenkins-plone-org please run jobs` directive for some time, albeit as an infrequent contributor, and read that comment many times and I only just recently came to understand something that seems important to communicate to less familiar contributors.  Namely that's it's best to get the repo-specific CI checks (e.g. GitHub actions, Travis CI, etc.) to passing *and then* launch the much longer running Plone Jenkins jobs as a final check before seeking review.  It seems worthwhile to improve that bot comment to make this clear.

### PR DESCRIPTION
**Pull request by rpatterson**
Clarify that usually contributors should get all other checks passing before running the
Plone Jenkins PR jobs and add a link to the Plone Jenkins docs.  Also fix some typos and
do some other editing for brevity and clarity.

Fixes #84

Also includes capturing some cleanup and local development build and set up I did along
the way.

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
I have no opinion on the Makefile, but the new comment is good for me.

**Comment by rpatterson** [comment]
Thanks for the review, @mauritsvanrees.  LMK if there's anything more I can do to get this merged.  CC: @gforcada

**Comment by gforcada** [comment]
Hey @rpatterson thanks for the PR! I LGTM though, the `Makefile` feels too much/unneeded for my taste, but oh well, we can always remove at a later point.

**Comment by gforcada** [comment]
Deployed! 🚀

**Pull request merged**
