### PR TITLE
Ignore plone-backend repo

### PR DESCRIPTION
**Pull request by gforcada**
For changelog entries

### CODE REVIEW

**Review by davisagli — APPROVED** [review]
I think we should start keeping a changelog for plone-backend, but until we do, this is good.

**Comment by gforcada** [comment]
@davisagli  indeed,  I'm not sure why it never occurred yo me 😅 maybe, as I'm basically the only one writing it and it is nit being released per se 🍀

**Comment by gforcada** [comment]
[File added](https://github.com/plone/mr.roboto/blob/master/CHANGES.rst) 😄 🍀

**Comment by davisagli** [comment]
@gforcada oh, actually I meant a changelog for plone-backend. I don't think a changelog for mr.roboto is important since we aren't releasing it and it is easy to check the commit log.

**Pull request merged**
