### PR TITLE
Zope support

### PR DESCRIPTION
**Pull request by MatthewWilkes**
This adds functionality to mr.roboto to understand the new procedure for Zope contributor agreements and install into all Zope repositories.

### CODE REVIEW

**Comment by gforcada** [comment]
I'm even fine just writing here :smiley: 

What's the idea then? :thinking:

**Comment by MatthewWilkes** [comment]
I'm in Los Angeles at the moment, Jazkarta are having an internal sprint/social and I thought I should get some work done on this.

@gforcada My understanding was that the CI/coredev.buildout/CHANGES functionality were not specific to the plone organisation, so they were unchanged. The big difference was that the contributor agreements to cover Zope things are in a different place.

You're right about adding mister-roboto to the Zope org, of course. I need to do some talking to the wider Zope community before we hit go on this, I thought maybe we could try a single package manually once it's all set up and test how that goes before the wider roll-out. In particular, we need to handle communications about contributor agreements.

As to the end state, I thought it was probably best to get Zope packages being treated the same as any Plone packages, so if they're in coredev they're core packages, if not they're not. I don't know if the CI will work correctly, 

@jensens @jugmac00 I wish I was in Halle with you all! I'm in LA right now, which is 9 hours behind you in terms of time. I guess you've gone for dinner now, but maybe we could chat first thing tomorrow if that's helpful?

**Comment by MatthewWilkes** [comment]
Urgh, I just typed a long reply and github ate it. I'll try and remember everything I said, but apologies if this ends up coming through twice..

@gforcada So, the idea is that we should get the Zope packages up to parity in terms of infrastructure helpers with Plone. Then, maybe there'll be Zope specific changes that people want to do, but we can't really know until we've got something running so I wanted to take the first steps.

My understanding is that the coredev buildout, travis and changelog verifier functions aren't specific to the Plone organisation. In particular, core packages are the ones listed in coredev, so that can include Zope packages too. The only parts that I could find that was specific to the plone organisation was the hook installation and the determination of if someone has signed the contributor agreement. For legal reasons we need to manage the contributor agreements separately for now, so I updated that to split out the Zope agreements from the existing Plone ones.

Are any of the things mister-roboto does right now definitely not applicable to Zope repos? If so, I can add code to exclude them, but they all seemed relevant to me.

@jugmac00 @jensens Wäre ich in Halle.. I'm currently in Los Angeles, Jazkarta are having their annual social sprint, and I thought I'd work on Zope admin things. It's ending today, but I won't be back in a European timezone until Saturday evening. I'm happy to talk about current status, but I guess you're all in a restaurant by now, as you're 9 hours ahead of me.

I can give a quick update here if you want to share it in the morning, and I'm happy to jump on a call first thing in the morning (for me) tomorrow. I'm not sure I'll still be awake at midnight my time/9am your time due to jetlag.

We were working hard on integrating both Zope and Pyramid into the Plone foundation, thinking that a lot of the administration work would be common for both communities and we didn't want to have people need to sign multiple new contributor agreements. Unfortunately, the Pyramid community pulled out, partially as they were concerned that the contributor agreement process was going to become less casual. We couldn't really accommodate that, as we've had legal advice on the best way of approaching things to be enforceable in the most countries.

There was a lot more admin for Pyramid, as the tech is less strongly connected to Plone, so we were working on a bunch of things at once. Now Pyramid has backed out we can forge ahead with the simpler admin for Zope.

We're hoping to announce a plan for contributor agreements at the end of this week or the start of next, but the new process *is* live, so if someone needs access to the Zope github repo you can send in the Plone contributor agreeement as normal but enter "Zope" as the programme instead of Plone. We'll all need to do this over the next few months, most likely, but we're not going to cut off access to people that haven't done that suddenly.

As for other things, there were some concerns about tax implications in the US but we've got those sorted now, we're waiting for the transfer of the money from the Zope Foundation to the Plone Foundation. If you haven't already you should email the Plone foundation about getting funding for the sprint, even if it's not strategic there are smaller awards for pizza (US tax law requires that such awards are for food. You don't need to provide receipts.).

**Comment by gforcada** [comment]
Revisiting this a few years after, with GitHub Actions and all the other tooling already available, I'm not sure if this is still worth pursuing 🤔 

I'm closing it, but please re-open if it still is worth keeping it open and merging it.

**Pull request closed without merging**
