### PR TITLE
Support for Plone 6.0 PR jobs

### PR DESCRIPTION
**Pull request by gforcada**

### CODE REVIEW

**Comment by jugmac00** [comment]
Hi Gil, I am pretty sure you know, but just in case. Some time ago GitHub implemented a `WIP` functionality... instead of typing `WIP` in the description field, you can use the drop down at the "Create PR" button and select something like "WIP PR".

**Comment by gforcada** [comment]
@jugmac00 if you push a single commit, github creates a PR with the name of that commit message I did not bother adding a better name, etc etc, it was mostly for me to test that mr.roboto was running after migrating the code to use a github token for authentication rather than using a username/password (which will get deprecated soon I was told).

**Comment by jugmac00** [comment]
Thanks for the heads up! I did not know that GitHub creates PRs automatically... I guess this is a project setting - as - e.g. in the Zope projects, I accidentially pushed to master several times, and there no PR was created.

**Review by mauritsvanrees — APPROVED** [review]
LGTM. See also https://github.com/plone/jenkins.plone.org/issues/275

Travis fails with `KeyError: 'plone_py3_versions'`. I guess that needs to be set in the test setup now, or in an `.ini` file.

Currently the `py3_tracked_versions` settings can contain the same Python versions for 5.2 and 6.0, but at some point Python 3.9 should be added to 6.0, if Zope supports it. I expect that we need fixes in Plone code though to support 3.9.
Anyway, for the current PR nothing needs to change just yet: it is something for the future.

**Comment by jensens** [comment]
looks better now, on a PR Jenkins tests for 6.0 with all 3.x versions are shown, but the link is missing to create a job and "please run jobs" has no effect.
manual start of the job works and it creates also feedback.

**Comment by jensens** [comment]
What is missing @plone/training-team to get the links on Github? I am happy to help if I get some pointers.

**Comment by fredvd** [comment]
Let's get this merged and live.   mr.roboto is running on the jenkins main server, I can update the pyramid app. There is no automatic deployment or versioning yet on that on the checkout, maybe we should introduce that as well. 

My biggest concern: When I restart the application how do/can we test this is working right afterwards?  Can we plan this somewhere this week that I update mr.roboto and @mauritsvanrees or @jensens can do some pull requests? 

Are other configuration updates needed on github, for example hooks?

**Comment by fredvd** [comment]
created a tag from whats installed now, merged this PR.  waiting for feedback to proceed.

**Comment by gforcada** [comment]
@fredvd `plone_py3_versions` this setting should be added most probably :thinking: sorry for being unresponsive, I'm having a hard time in live in general. Though, we can try to schedule a meeting to have a look at it (deploy) if you want

**Pull request merged**
