### PR TITLE
Fix TypeError when reading the coredev 6 documentation sources.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Fixes https://github.com/plone/mr.roboto/issues/85

### CODE REVIEW

**Review by ale-rt — APPROVED** [review]
LGTM and clearer

**Review by gforcada — APPROVED** [review]

**Comment by gforcada** [comment]
Merged and deployed 🎉

**Comment by gforcada** [comment]
Making some progress but the error is somehow still there 😕 

```
Traceback (most recent call last):
  File "/srv/mr.roboto/eggs/waitress-1.4.2-py3.6.egg/waitress/channel.py", line 349, in service
    task.service()
  File "/srv/mr.roboto/eggs/waitress-1.4.2-py3.6.egg/waitress/task.py", line 169, in service
    self.execute()
  File "/srv/mr.roboto/eggs/waitress-1.4.2-py3.6.egg/waitress/task.py", line 439, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/srv/mr.roboto/eggs/Paste-3.2.6-py3.6.egg/paste/urlmap.py", line 216, in __call__
    return app(environ, start_response)
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/view.py", line 771, in invoke_exception_view
    reraise_(*exc_info)
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/compat.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/view.py", line 767, in invoke_exception_view
    request_iface=request_iface.combined,
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/srv/mr.roboto/eggs/pyramid-1.10.4-py3.6.egg/pyramid/viewderivers.py", line 436, in rendered_view
    result = view(context, request)
  File "/srv/mr.roboto/src/mr.roboto/src/mr/roboto/security.py", line 40, in wrapped
    return fn(context, request)
  File "/srv/mr.roboto/src/mr.roboto/src/mr/roboto/views/home.py", line 128, in update_pickles
    get_sources_and_checkouts(request)
  File "/srv/mr.roboto/src/mr.roboto/src/mr/roboto/buildout.py", line 148, in get_sources_and_checkouts
    for source in buildout.sources:
  File "/srv/mr.roboto/src/mr.roboto/src/mr/roboto/buildout.py", line 83, in __iter__
    return self.data.__iter__()
  File "/srv/mr.roboto/src/mr.roboto/src/mr/roboto/buildout.py", line 77, in data
    source = Source().create_from_string(value)
  File "/srv/mr.roboto/src/mr.roboto/src/mr/roboto/buildout.py", line 37, in create_from_string
    setattr(self, key, value)
AttributeError: can't set attribute
```

**Comment by gforcada** [comment]
@mauritsvanrees should we try to sync next week/year (sorry, had to 😅 ) and see if we can iron it out?

**Comment by gforcada** [comment]
I see the problem, we try to set an attribute that is named `path` but we have a property on the class itself named `path` already. We should ignore it, as for mr.roboto it has no use 👍🏾

**Pull request merged**
