### PR TITLE
No changelog verifier needed for mockup.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
It uses release-it to create a changelog out of the commit messages.
See small discussion in Discord in the classic-ui channel.

### CODE REVIEW

**Review by petschki — APPROVED** [review]

**Review by davisagli — APPROVED** [review]

**Comment by gforcada** [comment]
Pushed to the server and restarted `mr.roboto`, please verify that it works 👍🏾

**Comment by petschki** [comment]
tested here and confirm that it works https://github.com/plone/mockup/pull/1245 ... thank you!

**Comment by mauritsvanrees** [comment]
Oh, you were slightly earlier. :-) Same test succeeds here.

**Comment by petschki** [comment]
# 🏎️💨

**Pull request merged**
